# This is a basic workflow to help you get started with Actions

name: linux scoop

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Runs a single command using the runners shell
#    - name: Setup Scoop
#      run: |
#        which pwsh
#        SCOOP="${HOME}/scoop/apps/current"
#        echo $SCOOP | xargs -I{} echo "::set-env name=SCOOP::{}"
#        git clone "https://github.com/lukesampson/scoop.git" ${SCOOP}

    # Runs a set of commands using the runners shell
    - name: Test Scoop
      run: |
        SCOOP="${HOME}/scoop"
        SCOOP_HOME="${SCOOP}/apps/scoop/current"
        git clone "https://github.com/lukesampson/scoop.git" ${SCOOP_HOME}
        ls -lsa ${SCOOP_HOME}
        pwsh "${SCOOP_HOME}/bin/install.ps1"
#        pwsh -File ". ${SCOOP_HOME}/test/bin/test.ps1"
#        echo $SCOOP | xargs -I{} echo "::set-env name=SCOOP::{}"

#        pwsh -File "$SCOOP/bin/scoop.ps1" help
