# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Runs a single command using the runners shell
    - name: Setup Scoop
      run: |
        which pwsh
        SCOOP="${HOME}/scoop/apps/current"
        echo $SCOOP | xargs -I{} echo "::set-env name=SCOOP::{}"
        git clone "https://github.com/lukesampson/scoop.git" ${SCOOP}

    # Runs a set of commands using the runners shell
    - name: Test Scoop
      run: |
        echo ${SCOOP}
        pwsh -File ${SCOOP}/bin/scoop.ps1 help
